[tool.poetry]
name = "herald"
version = "0.1.0"
description = "Fragment-based detection of candidate horizontal gene transfer events in aligned sequencing reads"
authors = ["Aaron Saporito", "Sophia Guerra"]
license = "MPL-2.0"
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.7"
tqdm = "^4.66.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
